//
//  QuoteWorker.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class QuoteAPIWorker
{
    func fetchQuote(success:@escaping([String:String])->Void, failure:@escaping (Error)->Void)
    {
        ServerHandler().fetchRandomQuote { (quote, err) in
            if let error = err{
                failure(error)
            }
            else if let quote_json = quote{
                success(quote_json)
            }
        }
    }
}
