//
//  QuoteRouter.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol QuoteRoutingLogic
{
  func routeToFavourites()
}

protocol QuoteDataPassing
{
  var dataStore: QuoteDataStore? { get }
}

class QuoteRouter: NSObject, QuoteRoutingLogic, QuoteDataPassing
{
    weak var viewController: QuoteViewController?
    var dataStore: QuoteDataStore?
    
    // MARK: Routing
    
    func routeToFavourites()
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "FavouriteQuotesViewController") as! FavouriteQuotesViewController
        navigateToFavourites(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToFavourites(source: QuoteViewController, destination: FavouriteQuotesViewController)
    {
        source.show(destination, sender: nil)
    }
    
}
