//
//  FavouriteQuotesRouter.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavouriteQuotesRoutingLogic
{
    func routeToSelectedQoutes()
}

protocol FavouriteQuotesDataPassing
{
    var dataStore: FavouriteQuotesDataStore? { get }
}

class FavouriteQuotesRouter: NSObject, FavouriteQuotesRoutingLogic, FavouriteQuotesDataPassing
{
    weak var viewController: FavouriteQuotesViewController?
    var dataStore: FavouriteQuotesDataStore?
    
    // MARK: Routing
    func routeToSelectedQoutes()
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "QuoteViewController") as! QuoteViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToQouteToHideFavbutton(source: dataStore!, destination: &destinationDS)
        passDataToQouteFavouriteRecord(source: dataStore!, destination: &destinationDS)
        navigateToQoute(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToQoute(source: FavouriteQuotesViewController, destination: QuoteViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToQouteToHideFavbutton(source: FavouriteQuotesDataStore, destination: inout QuoteDataStore)
    {
        destination.hideFavourites = true
    }
    
    func passDataToQouteFavouriteRecord(source: FavouriteQuotesDataStore, destination: inout QuoteDataStore)
    {
        destination.favouriteQuoteID = source.favQuoteID
    }
}
