//
//  FavouriteQuotesModels.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavouriteQuotes
{
    // MARK: Fetch all fav quotes
    
    enum Fetch
    {
        struct Request{}
        struct PassingRequest
        {
            var id:String
        }
        struct Response
        {
            var qoutes:[Quote]
        }
        struct ViewModel
        {
            struct DisplaybleItem {
                var quoteText:String
                var author:String
                var id:String
                var isFav:Bool
            }
            var quotes: [DisplaybleItem]
        }
    }
}
