//
//  FavouriteQuotesPresenter.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteQuotesPresentationLogic
{
  func presentAllFavouriteQuotes(response: FavouriteQuotes.Fetch.Response)
}

class FavouriteQuotesPresenter: FavouriteQuotesPresentationLogic
{
    weak var viewController: FavouriteQuotesDisplayLogic?
    
    // MARK: FavouriteQuotesPresentationLogic
    
    func presentAllFavouriteQuotes(response: FavouriteQuotes.Fetch.Response)
    {
        var items = [FavouriteQuotes.Fetch.ViewModel.DisplaybleItem]()
        for item in response.qoutes {
            items.append(FavouriteQuotes.Fetch.ViewModel.DisplaybleItem(quoteText: item.qoute!, author: item.author!, id: item.id!, isFav:item.isFavourite))
        }
        let viewModel = FavouriteQuotes.Fetch.ViewModel(quotes: items)
        viewController?.displayFavourites(viewModel: viewModel)
    }
}
