//
//  FavouriteQuotesInteractor.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteQuotesBusinessLogic
{
    func fetchAllFavouriteQuotes(request: FavouriteQuotes.Fetch.Request)
    func updateFavouriteQuote(request: FavouriteQuotes.Fetch.PassingRequest)
}

protocol FavouriteQuotesDataStore
{
    var favQuoteID: String { get set }
}

class FavouriteQuotesInteractor: FavouriteQuotesBusinessLogic, FavouriteQuotesDataStore
{
    var favQuoteID = ""
    var presenter: FavouriteQuotesPresentationLogic?
    var worker: FavouriteQuotesWorker?
    
    // MARK: FavouriteQuotesBusinessLogic
    func fetchAllFavouriteQuotes(request: FavouriteQuotes.Fetch.Request)
    {
        worker = FavouriteQuotesWorker()
        let favQuotes = worker?.fetchAllFavouriteQuotes()
        let response = FavouriteQuotes.Fetch.Response(qoutes: favQuotes!)
        presenter?.presentAllFavouriteQuotes(response: response)
    }
    
    func updateFavouriteQuote(request: FavouriteQuotes.Fetch.PassingRequest) {
        favQuoteID = request.id
    }
}
