//
//  FavouriteQuotesWorker.swift
//  RandomQuote
//
//  Created by Ravi kumar on 07/08/20.
//  Copyright (c) 2020 Ravi kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavouriteQuotesWorker
{
    func fetchAllFavouriteQuotes() -> [Quote]
    {
        let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
        return QuoteCoreDataStore(context: context).fetchAllFavourites()
    }
}
